version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  groups:
    nuget:
      patterns:
      - "*"
      update-types:
      - "major"
      - "minor"
      - "patch"
